name: primhub
description: "Aplicación para manejo de horas de soporte, entregables, cotizaciones y métricas."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  printing: ^5.12.0
  toastification: ^2.0.0
  universal_html: ^2.2.4
  file_picker: ^8.0.0+1
  desktop_drop: ^0.4.4
  super_drag_and_drop: ^0.9.1
  card_stack_swiper: ^1.1.1
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.1
  flutter_svg: ^2.3.0
  excel: ^4.0.6
  csv: ^8.0.0
  pdf: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
